name: Reusable Workflow

on:
  workflow_call:
    inputs:
      greeting:
        description: 'The greeting to print'
        required: true
      
jobs:
  reusable-job:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Hello, ${{ inputs.greeting }}!"
