name: Reusable Workflow 1

on:
  workflow_call:
  push:
    branches: [main]  # Trigger on pushes to the main branch

jobs:
  reusable-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify your desired Node.js version

      - name: Install dependencies
        run: npm ci

      # Replace with the actual task steps, utilizing Node.js
      - name: Perform Node.js task
        run: npm run my-task

      - name: Output results (optional)
        id: output-results
        run: |
          # Generate results or artifacts
          echo "Results: $RESULTS"
          echo "Artifacts: $ARTIFACTS"
        outputs:
          results: ${{ steps.output-results.outputs.RESULTS }}
          artifacts: ${{ steps.output-results.outputs.ARTIFACTS }}
