name: Reusable Workflow 1

on:
  workflow_call:
    

jobs:
  reusable-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Write something to log
        run: |
           echo : "Hello I am the test Case"





















        
