name: Reusable Workflow 1

on:
  workflow_call:

jobs:
  reusable-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Write something to log
        run: |
          echo "Running the reusbale workflow..."

      # Step 3: Print the current date and time
      - name: Print date and time
        run: date

      # Step 4: Print the contents of a file (optional)
      - name: Print file contents
        run: cat tREADME.md  # Replace with the desired file path
