name: Reusable Workflow 1

on:
  workflow_call:
    

jobs:
  reusable-job:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v3

      - name: Write something to log
        run: |
           echo : "Hello my name is Alam"





















        
